Repository Bloomly-xyz/campaign-manager, pull requests merged in 2023-02, with the labels that each got.

#7 Database creation and seed static data
  backend/API/CampaignManager.Api/.env
  backend/API/CampaignManager.Api/Extensions/RegisterDISerices.cs
  backend/Data/CampaignManager.Data/Context/DBContext.cs
  backend/Data/CampaignManager.Data/Migrations/20230221141423_CreateDatabase.Designer.cs
  backend/Data/CampaignManager.Data/Migrations/20230221141423_CreateDatabase.cs
  backend/Data/CampaignManager.Data/Migrations/DBContextModelSnapshot.cs
  backend/Data/CampaignManager.Data/Seed/Seed.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Common/HttpClient/HttpCall.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Common/HttpClient/IHttpCall.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/DBModels/BaseEntity.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/DBModels/CampaignUtilities.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/DBModels/Campaigns.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/DBModels/ClaimUtility.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/DBModels/EmailTemplates.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/DBModels/ShippingLocations.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/DBModels/ShippingPartner.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/DBModels/Users.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/DBModels/Utilities.cs
Labels: enhancement

#8 Be/fb user service
  backend/API/CampaignManager.Api/Program.cs
  backend/Business/CampaignManager.Business.Services/Interfaces/IUserService.cs
  backend/Business/CampaignManager.Business.Services/Services/UserService.cs
  backend/Business/CampaignManager.Business.ServicesTests/CampaignManager.Business.ServicesTests.csproj
  backend/Business/CampaignManager.Business.ServicesTests/Services/UserServiceTests.cs
  backend/Business/CampaignManager.Business.ServicesTests/appsettings.Development.json
  backend/Business/CampaignManager.Business.ServicesTests/appsettings.json
  backend/Data/CampaignManager.Data/IRepositpory/IUserRepository.cs
  backend/Data/CampaignManager.Data/Repositpory/UserRepository.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/CampaignManager.Infrastructure.Models.csproj
  backend/Infrastructure/CampaignManager.Infrastructure.Models/User/RequestModel/CreateUserRequest.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/User/ResponseModel/UserResponseModel.cs
Labels: enhancement

#10 S3 bucket and file operations
  backend/API/CampaignManager.Api/Controllers/S3BucketController.cs
  backend/Business/CampaignManager.Business.Services/Interfaces/IS3bucketService.cs
  backend/Business/CampaignManager.Business.Services/Services/S3bucketService.cs
  backend/Business/CampaignManager.Business.ServicesTests/CampaignManager.Business.ServicesTests.csproj
  backend/Business/CampaignManager.Business.ServicesTests/DependencyResolver/UnitTestDependencyResolver.cs
  backend/Business/CampaignManager.Business.ServicesTests/Services/S3bucketServiceTests.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Communication/AWS/S3Services/Bucket/BucketService.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Communication/AWS/S3Services/Bucket/IBucketService.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Communication/AWS/S3Services/File/FileService.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Communication/AWS/S3Services/File/IFileService.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/AWS/DTOs/S3ObjectDto.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/AWS/RequestModels/AWSS3RequestModel.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/AWS/RequestModels/UploadFileRequest.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/CampaignManager.Infrastructure.Models.csproj
Labels: enhancement

#9 Installation Of Front End Project Dependencies
  frontend/package-lock.json
  frontend/package.json
  frontend/tailwind.config.js
Labels: enhancement

#18 Utility Service with unit test implementation
  backend/Business/CampaignManager.Business.Services/Interfaces/IUtilityService.cs
  backend/Business/CampaignManager.Business.Services/Services/UtilityService.cs
  backend/Business/CampaignManager.Business.ServicesTests/Services/S3bucketServiceTests.cs
  backend/Business/CampaignManager.Business.ServicesTests/Services/UtilityServiceTests.cs
  backend/Data/CampaignManager.Data/IRepositpory/IUtilityRepository.cs
  backend/Data/CampaignManager.Data/Repositpory/UtilityRepository.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/Utilities/RequestModels/ClaimUtilityRequestModel.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/Utilities/ResponseModels/ShippingPartnerResponseModel.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/Utilities/ResponseModels/UtilitiesResponseModel.cs
Labels: enhancement

#17 Campaign related APIs, Services and repositories
  backend/API/CampaignManager.Api/Controllers/CampaignController.cs
  backend/API/CampaignManager.Api/Extensions/RegisterDISerices.cs
  backend/Business/CampaignManager.Business.Services/Interfaces/ICampaignService.cs
  backend/Business/CampaignManager.Business.Services/Services/CampaignService.cs
  backend/Business/CampaignManager.Business.ServicesTests/Common/CommonModel.cs
  backend/Business/CampaignManager.Business.ServicesTests/Services/CampaignServiceTests.cs
  backend/Data/CampaignManager.Data/IRepositpory/ICampaignRepository.cs
  backend/Data/CampaignManager.Data/Repositpory/CampaignRepository.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/CampaignModel/Dtos/CampaignUtilityData.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/CampaignModel/RequestModel/CampaignRequestModel.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/CampaignModel/RequestModel/CampainUtilitiesRequest.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/CampaignModel/ResponseModel/CampaignResponseModel.cs
Labels: enhancement

#19 Add User and Utility Controllers
  backend/API/CampaignManager.Api/Controllers/UserController.cs
  backend/API/CampaignManager.Api/Controllers/UtilityController.cs
Labels: good first issue

#20 Campaign and utility Service Code Merge Request
  .gitignore
  backend/API/CampaignManager.Api/Controllers/CampaignController.cs
  backend/API/CampaignManager.Api/Controllers/UserController.cs
  backend/API/CampaignManager.Api/Controllers/UtilityController.cs
  backend/API/CampaignManager.Api/Extensions/RegisterDISerices.cs
  backend/Business/CampaignManager.Business.Services/Interfaces/ICampaignService.cs
  backend/Business/CampaignManager.Business.Services/Interfaces/IUtilityService.cs
  backend/Business/CampaignManager.Business.Services/Services/CampaignService.cs
  backend/Business/CampaignManager.Business.Services/Services/UtilityService.cs
  backend/Business/CampaignManager.Business.ServicesTests/Common/CommonModel.cs
  backend/Business/CampaignManager.Business.ServicesTests/Services/CampaignServiceTests.cs
  backend/Business/CampaignManager.Business.ServicesTests/Services/S3bucketServiceTests.cs
  backend/Business/CampaignManager.Business.ServicesTests/Services/UtilityServiceTests.cs
  backend/Data/CampaignManager.Data/IRepositpory/ICampaignRepository.cs
  backend/Data/CampaignManager.Data/IRepositpory/IUtilityRepository.cs
  backend/Data/CampaignManager.Data/Repositpory/CampaignRepository.cs
  backend/Data/CampaignManager.Data/Repositpory/UtilityRepository.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/CampaignModel/Dtos/CampaignUtilityData.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/CampaignModel/RequestModel/CampaignRequestModel.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/CampaignModel/RequestModel/CampainUtilitiesRequest.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/CampaignModel/ResponseModel/CampaignResponseModel.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/Utilities/RequestModels/ClaimUtilityRequestModel.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/Utilities/ResponseModels/ShippingPartnerResponseModel.cs
  backend/Infrastructure/CampaignManager.Infrastructure.Models/Utilities/ResponseModels/UtilitiesResponseModel.cs
  backend/README.md
Labels: enhancement

#26 BlockChain Tx & Scripts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/android-chrome-192x192.png
  frontend/public/android-chrome-512x512.png
  frontend/public/apple-touch-icon.png
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/mstile-150x150.png
  frontend/src/BlockChainTx/BlockChainScripts.js
  frontend/src/BlockChainTx/BlockChainTx.js
  frontend/src/BlockChainTx/MultiSignature.js
  frontend/src/index.css
  frontend/src/logo.svg
Labels: bug, enhancement

#27 Campaign end date issues fixed
  backend/Data/CampaignManager.Data/Repositpory/CampaignRepository.cs
Labels: bug

#30 [Bugs Fixed]: Timer issues, user Id issues, campaign id Issues, and UI fixes
  frontend/src/assets/images/Circle-checked-icon.svg
  frontend/src/components/campaign-creation/CampaignCreateComponents/CommunityTargeting.jsx
  frontend/src/components/campaign-creation/CampaignCreation.jsx
  frontend/src/components/claim-utility-components/ClaimUtilityComponents/ClaimUtilityTimer.jsx
  frontend/src/components/claim-utility-components/ClaimUtilityContent.jsx
  frontend/src/components/modals-components/ClaimUtilityModal.jsx
  frontend/src/constants/images-constants/images.js
  frontend/src/helpers/BlockChainErrorsHandler.js
Labels: bug

#34 Resolve CORS Issue
  Images/DotNet.png
  Images/flow.png
  Images/node.png
  backend/API/CampaignManager.Api/Program.cs
Labels: bug

#35 Update CORS URL
  backend/API/CampaignManager.Api/Program.cs
Labels: bug

#36 Merge Frontend Into Main
  frontend/public/index.html
  frontend/src/assets/images/merch-icon-white.svg
  frontend/src/assets/images/merch-icon.svg
  frontend/src/components/campaign-creation/CampaignCreateComponents/AttachUtilityComponents/AttachUtilityCheckbox.jsx
  frontend/src/components/claim-utility-components/ClaimUtilityContent.jsx
  frontend/src/components/common/ui-components/sidebar-menus-component/MenuItem.jsx
  frontend/src/components/nft-campaign-components/NFTCompaignListing.jsx
  frontend/src/constants/images-constants/images.js
Labels: bug, enhancement

#37 Add frontend URLs to resolve CORS Issue
  backend/API/CampaignManager.Api/Program.cs
Labels: enhancement

#38 Bug Fixing
  frontend/public/android-chrome-192x192.png
  frontend/public/android-chrome-512x512.png
  frontend/public/apple-touch-icon.png
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/public/favicon.ico
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/src/assets/images/auth-right-bg.png
  frontend/src/components/auth-component/BloctoAuth.jsx
  frontend/src/components/campaign-creation/CampaignCreateComponents/AttachUtilityComponents/AllUtility.jsx
  frontend/src/components/campaign-creation/CampaignCreateComponents/AttachUtilityComponents/PhysicalUtility.jsx
  frontend/src/components/campaign-creation/CampaignCreation.jsx
  frontend/src/components/claim-utility-components/ClaimUtilityContent.jsx
  frontend/src/components/modals-components/MintNftModal.jsx
Labels: bug

#39 Update Cors Issue
  backend/API/CampaignManager.Api/Program.cs
Labels: bug

#40 UI enhancements & Textual changes
  frontend/src/assets/images/Eye On.svg
  frontend/src/assets/images/add more field icon.svg
  frontend/src/assets/images/addMoreIcon.svg
  frontend/src/components/auth-component/AuthRightContent.jsx
  frontend/src/components/auth-component/BloctoAuth.jsx
  frontend/src/components/campaign-creation/CampaignCreateComponents/AttachUtility.jsx
  frontend/src/components/campaign-creation/CampaignCreateComponents/AttachUtilityComponents/AllUtility.jsx
  frontend/src/components/claim-utility-components/ClaimUtilityContent.jsx
  frontend/src/components/common/ui-components/sidebar-menus-component/MenuItem.jsx
  frontend/src/components/modals-components/ClaimUtilityModal.jsx
  frontend/src/components/modals-components/MintNftModal.jsx
  frontend/src/components/nft-campaign-components/NFTCompaignListing.jsx
  frontend/src/components/nft-campaign-components/NftCampaignListingComponent/NftCampaignColumns.js
  frontend/src/constants/images-constants/images.js
Labels: enhancement

#41 Merge Front End repo into Main branch
  frontend/src/assets/images/Eye On.svg
  frontend/src/assets/images/add more field icon.svg
  frontend/src/assets/images/addMoreIcon.svg
  frontend/src/components/auth-component/AuthRightContent.jsx
  frontend/src/components/auth-component/BloctoAuth.jsx
  frontend/src/components/campaign-creation/CampaignCreateComponents/AttachUtility.jsx
  frontend/src/components/campaign-creation/CampaignCreateComponents/AttachUtilityComponents/AllUtility.jsx
  frontend/src/components/claim-utility-components/ClaimUtilityContent.jsx
  frontend/src/components/common/ui-components/sidebar-menus-component/MenuItem.jsx
  frontend/src/components/modals-components/ClaimUtilityModal.jsx
  frontend/src/components/modals-components/MintNftModal.jsx
  frontend/src/components/nft-campaign-components/NFTCompaignListing.jsx
  frontend/src/components/nft-campaign-components/NftCampaignListingComponent/NftCampaignColumns.js
  frontend/src/constants/images-constants/images.js
Labels: enhancement

#44 Frontend Merge into main
  frontend/src/assets/images/Bloomly_White.svg
  frontend/src/components/auth-component/AuthRightContent.jsx
  frontend/src/constants/images-constants/images.js
Labels: enhancement

#45 Merge Front End Into Main
  frontend/src/components/modals-components/ClaimUtilityModal.jsx
Labels: bug

#46 Merge FrontEnd into Main
  frontend/src/components/claim-utility-components/ClaimUtilityContent.jsx
Labels: bug
